language: python
python:
  - "3.6"

before_install:
  - sudo rm -f /etc/boto.cfg
  
env:
  - AWS_DEFAULT_REGION=us-east-1 DYNAMODB_TABLE_K8_CLUSTERS=hyper-kube-config-test

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script: python -m unittest discover -s tests/ -p "*.py"